import React, {useRef} from 'react';
import {View, StyleSheet, Pressable} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import type {DrawerContentComponentProps} from '@react-navigation/drawer';
import {
  useSettings,
  useTheme,
  useTranslation,
} from '../providers/SettingsProvider';
import {Typography} from '../../components/Typography';
import {AttentionDot} from '../../components/AttentionDot';
import {useNotificationAttention} from '../providers/NotificationAttentionProvider';

export function DrawerContent({navigation}: DrawerContentComponentProps) {
  const theme = useTheme();
  const insets = useSafeAreaInsets();
  const {attention} = useNotificationAttention();
  const {t, setLanguage, language} = useTranslation();
  const {beginThemeTransition, scheme} = useSettings();
  const toggleRef = useRef<View>(null);

  // The autogenerated `View` ref exposes measureInWindow; the Pressable wraps
  // it. This reads the toggle's real on-screen position so the wave expands
  // from the exact place the user pressed.
  function handleThemeToggle() {
    toggleRef.current?.measureInWindow((x, y, w, h) => {
      beginThemeTransition({x: x + w / 2, y: y + h / 2});
    });
  }

  // The drawer is nested inside the root stack, so its "Login"/"Settings"
  // destinations live one level up on the parent navigator.
  function go(screen: 'Login' | 'Settings') {
    navigation.closeDrawer();
    navigation.getParent()?.navigate(screen);
  }

  const currentThemeLabel = scheme === 'light' ? t('theme.light') : t('theme.dark');
  const nextThemeLabel = scheme === 'light' ? t('theme.dark') : t('theme.light');

  return (
    <View
      style={[
        styles.container,
        {
          backgroundColor: theme.colors.surface,
          paddingTop: insets.top + theme.spacing.xxl,
          paddingBottom: insets.bottom + theme.spacing.xxl,
        },
      ]}>
      <View style={styles.top}>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={t('drawer.login')}
          style={({pressed}) => [
            styles.item,
            {backgroundColor: pressed ? theme.colors.border : theme.colors.successSurface},
          ]}
          onPress={() => go('Login')}>
          <Typography
            size="lg"
            weight="semibold"
            color={theme.colors.primaryDark}
            align="center">
            {t('drawer.login')}
          </Typography>
        </Pressable>
      </View>

      <View style={styles.middle}>
        <View
          ref={toggleRef}
          collapsable={false}
          style={[styles.themeCard, {borderColor: theme.colors.border}]}>
          <Pressable
            accessibilityRole="switch"
            accessibilityLabel={t('drawer.theme')}
            accessibilityState={{checked: scheme === 'dark'}}
            accessibilityHint={t('drawer.themeHint')}
            onPress={handleThemeToggle}
            style={({pressed}) => [
              styles.themeToggle,
              {backgroundColor: pressed ? theme.colors.border : theme.colors.surface},
            ]}>
            <View style={styles.themeIcon}>
              <Typography size="lg">{scheme === 'light' ? '☀️' : '🌙'}</Typography>
            </View>
            <View style={styles.themeText}>
              <Typography
                size="md"
                weight="semibold"
                color={theme.colors.primaryText}>
                {t('drawer.theme')}
              </Typography>
              <Typography
                size="xs"
                color={theme.colors.secondaryText}
                style={styles.themeValue}>
                {currentThemeLabel}
              </Typography>
            </View>
            <Typography size="sm" color={theme.colors.secondaryText}>
              {nextThemeLabel}
            </Typography>
          </Pressable>
        </View>

        <Pressable
          accessibilityRole="button"
          accessibilityLabel={t('drawer.settings')}
          style={({pressed}) => [
            styles.item,
            {backgroundColor: pressed ? theme.colors.border : theme.colors.successSurface},
          ]}
          onPress={() => go('Settings')}>
          <Typography
            size="lg"
            weight="semibold"
            color={theme.colors.primaryDark}
            align="center">
            {t('drawer.settings')}
          </Typography>
          <AttentionDot active={attention} style={styles.menuDot} />
        </Pressable>
      </View>

      <View style={styles.bottom}>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={language === 'fa' ? 'English' : 'فارسی'}
          onPress={() => setLanguage(language === 'fa' ? 'en' : 'fa')}
          style={({pressed}) => [
            styles.item,
            {backgroundColor: pressed ? theme.colors.border : theme.colors.surface},
          ]}>
          <Typography
            size="md"
            weight="semibold"
            color={theme.colors.primaryText}
            align="center">
            {language === 'fa' ? 'فارسی' : 'English'}
          </Typography>
          <Typography size="xs" color={theme.colors.secondaryText} align="center">
            {language === 'fa' ? 'English' : 'فارسی'}
          </Typography>
        </Pressable>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  top: {
    alignSelf: 'stretch',
  },
  middle: {
    marginTop: 24,
  },
  bottom: {
    alignSelf: 'stretch',
    marginTop: 'auto',
  },
  menuDot: {
    top: -3,
    right: -3,
  },
  item: {
    minHeight: 54,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    marginBottom: 12,
  },
  themeCard: {
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 12,
    overflow: 'hidden',
  },
  themeToggle: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  themeIcon: {
    width: 36,
    alignItems: 'center',
  },
  themeText: {
    flex: 1,
    marginStart: 8,
  },
  themeValue: {
    marginTop: 2,
  },
});
