import React, {useRef, useState} from 'react';
import {View, StyleSheet, Pressable, Modal, Image} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import type {DrawerContentComponentProps} from '@react-navigation/drawer';
import {
  useSettings,
  useTheme,
  useTranslation,
} from '../providers/SettingsProvider';
import {Typography} from '../../components/Typography';
import {AttentionDot} from '../../components/AttentionDot';
import {useNotificationAttention} from '../providers/NotificationAttentionProvider';

const HELP_BENEFITS = [
  'help.benefit1',
  'help.benefit2',
  'help.benefit3',
  'help.benefit4',
  'help.benefit5',
] as const;

export function DrawerContent({navigation}: DrawerContentComponentProps) {
  const theme = useTheme();
  const insets = useSafeAreaInsets();
  const {attention} = useNotificationAttention();
  const {t, setLanguage, language} = useTranslation();
  const {beginThemeTransition, scheme} = useSettings();
  const toggleRef = useRef<View>(null);
  const [helpOpen, setHelpOpen] = useState(false);

  // The autogenerated `View` ref exposes measureInWindow; the Pressable wraps
  // it. This reads the toggle's real on-screen position so the wave expands
  // from the exact place the user pressed.
  function handleThemeToggle() {
    toggleRef.current?.measureInWindow((x, y, w, h) => {
      beginThemeTransition({x: x + w / 2, y: y + h / 2});
    });
  }

  // The drawer is nested inside the root stack, so its "Login"/"Settings"
  // destinations live one level up on the parent navigator.
  function go(screen: 'Login' | 'Settings') {
    navigation.closeDrawer();
    navigation.getParent()?.navigate(screen);
  }

  const currentThemeLabel = scheme === 'light' ? t('theme.light') : t('theme.dark');
  const nextThemeLabel = scheme === 'light' ? t('theme.dark') : t('theme.light');

  return (
    <View
      style={[
        styles.container,
        {
          backgroundColor: theme.colors.surface,
          paddingTop: insets.top + theme.spacing.xxl,
          paddingBottom: insets.bottom + theme.spacing.xxl,
        },
      ]}>
      <View style={styles.top}>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={t('drawer.login')}
          style={({pressed}) => [
            styles.item,
            {backgroundColor: pressed ? theme.colors.border : theme.colors.successSurface},
          ]}
          onPress={() => go('Login')}>
          <Typography
            size="lg"
            weight="semibold"
            color={theme.colors.primaryDark}
            align="center">
            {t('drawer.login')}
          </Typography>
        </Pressable>
      </View>

      <View style={styles.middle}>
        <View
          ref={toggleRef}
          collapsable={false}
          style={[styles.themeCard, {borderColor: theme.colors.border}]}>
          <Pressable
            accessibilityRole="switch"
            accessibilityLabel={t('drawer.theme')}
            accessibilityState={{checked: scheme === 'dark'}}
            accessibilityHint={t('drawer.themeHint')}
            onPress={handleThemeToggle}
            style={({pressed}) => [
              styles.themeToggle,
              {backgroundColor: pressed ? theme.colors.border : theme.colors.surface},
            ]}>
            <View style={styles.themeIcon}>
              <Typography size="lg">{scheme === 'light' ? '☀️' : '🌙'}</Typography>
            </View>
            <View style={styles.themeText}>
              <Typography
                size="md"
                weight="semibold"
                color={theme.colors.primaryText}>
                {t('drawer.theme')}
              </Typography>
              <Typography
                size="xs"
                color={theme.colors.secondaryText}
                style={styles.themeValue}>
                {currentThemeLabel}
              </Typography>
            </View>
            <Typography size="sm" color={theme.colors.secondaryText}>
              {nextThemeLabel}
            </Typography>
          </Pressable>
        </View>

        <Pressable
          accessibilityRole="button"
          accessibilityLabel={t('drawer.settings')}
          style={({pressed}) => [
            styles.item,
            {backgroundColor: pressed ? theme.colors.border : theme.colors.successSurface},
          ]}
          onPress={() => go('Settings')}>
          <Typography
            size="lg"
            weight="semibold"
            color={theme.colors.primaryDark}
            align="center">
            {t('drawer.settings')}
          </Typography>
          <AttentionDot active={attention} style={styles.menuDot} />
        </Pressable>

        <Pressable
          accessibilityRole="button"
          accessibilityLabel={t('drawer.help')}
          style={({pressed}) => [
            styles.item,
            {backgroundColor: pressed ? theme.colors.border : theme.colors.surface},
          ]}
          onPress={() => setHelpOpen(true)}>
          <Typography
            size="lg"
            weight="semibold"
            color={theme.colors.primaryText}
            align="center">
            {t('drawer.help')}
          </Typography>
        </Pressable>
      </View>

      <View style={styles.bottom}>
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={language === 'fa' ? 'English' : 'فارسی'}
          onPress={() => setLanguage(language === 'fa' ? 'en' : 'fa')}
          style={({pressed}) => [
            styles.item,
            {backgroundColor: pressed ? theme.colors.border : theme.colors.surface},
          ]}>
          <Typography
            size="md"
            weight="semibold"
            color={theme.colors.primaryText}
            align="center">
            {language === 'fa' ? 'فارسی' : 'English'}
          </Typography>
          <Typography size="xs" color={theme.colors.secondaryText} align="center">
            {language === 'fa' ? 'English' : 'فارسی'}
          </Typography>
        </Pressable>
      </View>

      <Modal
        visible={helpOpen}
        transparent
        animationType="fade"
        onRequestClose={() => setHelpOpen(false)}>
        <View
          style={[
            styles.helpOverlay,
            {paddingTop: insets.top + 16, paddingBottom: insets.bottom + 16},
          ]}>
          <Pressable
            accessibilityRole="button"
            accessibilityLabel={t('help.close')}
            onPress={() => setHelpOpen(false)}
            style={[StyleSheet.absoluteFill, styles.helpScrim, {backgroundColor: theme.colors.black}]}
          />
          <View style={styles.helpCard}>
            <Image
              source={require('../../assets/help-page.png')}
              resizeMode="contain"
              style={styles.helpCardImage}
            />
            <View style={styles.helpContent}>
              <Typography
                size="lg"
                weight="semibold"
                color={theme.colors.ink}
                align="center"
                style={styles.helpTitle}>
                {t('help.title')}
              </Typography>
              <View style={styles.helpList}>
                {HELP_BENEFITS.map(key => (
                  <Typography
                    key={key}
                    size="sm"
                    color={theme.colors.ink}
                    style={styles.helpBullet}>
                    • {t(key)}
                  </Typography>
                ))}
              </View>
            </View>
            <Pressable
              accessibilityRole="button"
              accessibilityLabel={t('help.close')}
              onPress={() => setHelpOpen(false)}
              style={({pressed}) => [
                styles.helpClose,
                {backgroundColor: theme.colors.error},
                pressed && styles.helpClosePressed,
              ]}>
              <Typography
                size="lg"
                weight="semibold"
                color={theme.colors.white}
                align="center">
                ✕
              </Typography>
            </Pressable>
          </View>
        </View>
      </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  top: {
    alignSelf: 'stretch',
  },
  middle: {
    marginTop: 24,
  },
  bottom: {
    alignSelf: 'stretch',
    marginTop: 'auto',
  },
  menuDot: {
    top: -3,
    right: -3,
  },
  item: {
    minHeight: 54,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    marginBottom: 12,
  },
  themeCard: {
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 12,
    overflow: 'hidden',
  },
  themeToggle: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  themeIcon: {
    width: 36,
    alignItems: 'center',
  },
  themeText: {
    flex: 1,
    marginStart: 8,
  },
  themeValue: {
    marginTop: 2,
  },
  helpOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  helpScrim: {
    opacity: 0.55,
  },
  helpCard: {
    width: '100%',
    maxWidth: 400,
    // Match the photo's own 848x1264 ratio so the card frames the photo
    // exactly (the zoomed image then fills it edge-to-edge).
    aspectRatio: 848 / 1264,
    borderRadius: 20,
    overflow: 'hidden',
  },
  // The photo has a ~160px dark frame on every side; scaling 1.7x about the
  // center crops the frame off all edges so every text line sits on
  // parchment (visible window: src x175-673, y260-1004, all bright).
  helpCardImage: {
    ...StyleSheet.absoluteFillObject,
    transform: [{scale: 1.7}],
  },
  helpContent: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  // `Gulzar` is a Nastaliq (handwritten-style) face; its deep descenders need
  // generous line heights or glyphs clip.
  helpTitle: {
    fontFamily: 'Gulzar',
    lineHeight: 36,
  },
  helpList: {
    marginTop: 16,
  },
  helpBullet: {
    fontFamily: 'Gulzar',
    marginTop: 10,
    lineHeight: 30,
  },
  helpClose: {
    position: 'absolute',
    bottom: 12,
    alignSelf: 'center',
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpClosePressed: {
    opacity: 0.75,
  },
});
